version: "3.9"
services:
  discovery:
    image: discovery-image
    ports:
      - "2001:2001"
    networks:
      - keycloak_network
  gateway:
    depends_on:
    - discovery
    image: gateway-image
    ports:
      - "8089:8089"
      - "5005:5005"
    networks:
      - keycloak_network
  mock-service:
    depends_on:
    - discovery
    image: mock-service-image
    ports:
      - "8090:8090"
    networks:
      - keycloak_network
  db:
    image: 'bitnami/postgresql:11'
    environment:
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=keycloak
    ports:
      - '5432:5432'
    networks:
      - keycloak_network
  keycloak:
    image: bitnami/keycloak:19.0.2
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=DEBUG
      - DB_VENDOR=POSTGRES
      - DB_ADDR=db
      - DB_PORT_NUMBER=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
    depends_on:
      - db
    networks:
      - keycloak_network
networks:
  keycloak_network:
    driver: bridge
    name: keycloak_network
